### ISSUE TITLE
What was life like before you moved to Canada?

### ISSUE THREAD

**Issue by pearlchen** [ahmadnassri/ama#10]

**Comment by ahmadnassri** [comment]
I actually covered this in detail here: https://www.ahmadnassri.com/blog/the-story-so-far-part-1/ and some here: https://www.ahmadnassri.com/blog/opting-into-the-matrix/

###### tl;dr

- "hacking" since as long as I can remember
- everything is different, not better or worse, just different way of living
- daily life is simpler, but history of religious and political conflicts still take hold
- that history brews hate and intolerance, and eventually wars as you see today
- never going back, never want to go back, have no regrets or desire to see people there
- would go back as a tourist of ancient history and past civilizations, that's all.
- contrary to what some might believe, US & Canada are the exception to the rest of the world, I compare this to [living in the Matrix](https://www.ahmadnassri.com/blog/opting-into-the-matrix/)

**Comment by pearlchen** [comment]
You were such a hustler :P

**Comment by ahmadnassri** [comment]
"were"? ;)
