### ISSUE TITLE
What is the best way to learn API development?

### ISSUE THREAD

**Issue by CarlMungazi** [ahmadnassri/ama#17]
Hi Ahmad,

Thanks for making this AMA :+1: 

I'm a journalist and for the last year I've been scratching my long-term tech itch by learning how to code. Working with data has always been an interest of mine and lately I've been getting into APIs. What would you recommend as the best way to learn API development? 

I want to build a web app which tracks various news sources (train times, food hygiene ratings, crime data etc) using the APIs each source provides. I've seen a couple of tutorials but can't seem to get my head around it.

**Comment by ahmadnassri** [comment]
there are two paths in my opinion:

### the hard way:
- start by reading about the HTTP Spec, [_RFC 2616_](https://tools.ietf.org/html/rfc2616), then its evolution into [_RFC 723*_](http://httpwg.github.io/specs/)
- gain extra points by learning about [HTTP2](https://httpwg.github.io/specs/rfc7540.html)
- learn about API Documentation Languages such as Swagger/OAI, API Blueprint, RAML, etc ...
- pick a service you like to use often (e.g. Twitter, or Facebook)
- build a simple use of these products using their APIS
  - e.g. Twitter: build a stream of tweets from the people you follow
  - e.g. Facebook: build a wall / post feed
- build interactions: 
  - Tweet through the API
  - Upload an image to FAcebook through the API 

if you follow those steps it will give you the entire background knowledge needed for understanding APIs / HTTP and the principles on which they operate, along with covering 99% of the API use cases (consuming & posting data)

### the easy way:

- most API providers provide SDKs, which would mean learning and following the examples of each provider's SDK, none are exactly the same, nor similar.
  - while this might seem like more work, it really is less, since you're just using a library of your favorite language, and letting it deal with all the internals of HTTP / API communication without having to learn what that means

- find the most popular HTTP client library in your favorite language *(shameless self promotion: [unirest.io](http://unirest.io/))* and learn that, then every API you want to consume afterwards can be consumed with the same library.

- most APIs tend to focus on [C.R.U.D](https://en.wikipedia.org/wiki/Create,_read,_update_and_delete) operations represented through HTTP actions: POST, GET, PATCH, DELETE, which 99% of said client libraries support out of the box.
