### ISSUE TITLE
What are your thoughts on Google Glass?

### ISSUE THREAD

**Issue by sindresorhus** [ahmadnassri/ama#3]

**Comment by ahmadnassri** [comment]
I've been [strong](https://www.ahmadnassri.com/talks/wwto-google-glass-reunion/) and [persistent](https://www.ahmadnassri.com/talks/google-glass-at-the-rom/) [advocate](https://www.ahmadnassri.com/projects/glass-reactions/) of Google Glass for a long time, even [before](https://www.ahmadnassri.com/blog/google-glass-human-computer-interaction/) I got one!

though in the past few weeks, I've never put it one once. more accurately, ever since I got the [LG Watch Urbane](https://twitter.com/AhmadNassri/status/605941578813743106)

![image](https://cloud.githubusercontent.com/assets/183195/8631475/069f74c4-2745-11e5-8238-4d31fff28461.png)

I still believe in the form factor, I will still wear my Google Glass, but without a stronger commitment from Google to strengthen the developer community around it, its nothing but a notifications hub right now ... something a Smart Watch does very well, and even better.

that said, I'll be putting my Glass on for every bike and motorbike ride this summer, and keeping my wrist free, don't think the watch serves the sports market as well as the Glass form factor.
