### ISSUE TITLE
What do you think of the AMA thing?

### ISSUE THREAD

**Issue by sindresorhus** [ahmadnassri/ama#7]

**Comment by ahmadnassri** [comment]
very interesting, especially since I've been working on a project to better surface the "hacker culture" to the rest of the world (none-tech aware folks) ...

so i'm watching this very closely as believe there are some great learning from all these amas especially as i'm about to announce http://hacker.bio/ in the next few weeks. (which I'll be tapping you for participating too @sindresorhus :wink: )

**Comment by sindresorhus** [comment]
I've found it really interesting to ask and read questions, especially how people got started in this industry. Will definitely participate in your hacker.bio thing ;)

**Comment by ahmadnassri** [comment]
>  especially how people got started in this industry. 

exactly, and what KEEPS them in it!

> Will definitely participate in your hacker.bio thing ;)

:+1:
