### ISSUE TITLE
Why do you work on open source?

### ISSUE THREAD

**Issue by sindresorhus** [ahmadnassri/ama#8]

**Comment by ahmadnassri** [comment]
I honestly can't even understand why would anybody want to do *anything but* open source!?

no really, I don't! 

I know that's not answering the question directly though, so here's another attempt:

open source seems like the natural way of *being*, anything else, does not make sense, this is not even a software/hardware only thing, there's something to be said about extending the open source mindset beyond the technical realms, and into art, culture, fashion, and life in general.

we share because we care.
we share because we want to learn and better ourselves and others.
we share and work together to make the world a better place.
